### PR TITLE
Add constraint on bokeh and pandas version

### PR DESCRIPTION
**Pull request by gwenzek**
pandas-bokeh has a requirement on bokeh.transform.cumsum, which was added in June 2018 to bokeh: https://github.com/bokeh/bokeh/commit/28a7f8c0fde9f058318a2ec0e5ee851d8187ec1d
I have tested with 1.2.0, but it probably also work with 1.0.0

Similarly using Pandas 0.22.0 I was getting the following error:

```
/private/home/guw/.conda/envs/fair_apex/lib/python3.6/site-packages/pandas_bokeh/__init__.py:24: Warning: Could not define plot method for Pandas DataFrame and Series. Please make sure that Pandas is installed if you wish to use Bokeh as plotting backend for Pandas.

Exceptions: cannot import name 'CachedAccessor'
```

### CODE REVIEW

File: setup.py [hunk 1]
```diff
@@ -68,7 +68,7 @@
     long_description_content_type="text/markdown",
     url="https://github.com/PatrikHlobil/Pandas-Bokeh",
     packages=setuptools.find_packages(),
-    install_requires=["bokeh", "pandas"],
+    install_requires=["bokeh >=1.2.0", "pandas >=0.24.2"],
```
Comment (PatrikHlobil) [inline setup.py]: I think it should work with bokeh >=1.0 and pandas > 0.23. I normally develop against the most recent releases of both. I really have to try this out at some point. Maybe I could change my tox.ini file to try that ...

Could you check Bokeh 1.0 & pandas 0.23 please?

Comment (gwenzek) [reply setup.py]: Done, it also works with bokeh >=1.0.0 and pandas >=0.23.0

**Comment by PatrikHlobil** [comment]
Looks good now. I will merge. Thanks for your help 😉🙏. Best Patrik

**Comment by gwenzek** [comment]
Thanks you for making this very nice library !
