### ISSUE TITLE
Pandas version mismatch

### ISSUE THREAD

**Issue by zifeo** [PatrikHlobil/Pandas-Bokeh#62]
Using latest pandas (1.0.3) and latest pandas-bokeh, I get: `ImportError: cannot import name 'BasePlotMethods' from 'pandas.plotting._core' (/usr/local/lib/python3.7/site-packages/pandas/plotting/_core.py)`. What can be done to overcome that?

**Comment by ianozsvald** [comment]
I have a fresh Python 3.8 environment, using conda, with Pandas 1.0.3 and the latest pandas-bokeh and I _don't_ have any problems. Can you state if you made a fresh environment or if you've upgraded? Providing other version details would help.

Here's mine (using `watermark`):
![image](https://user-images.githubusercontent.com/273210/79693133-dc236580-8260-11ea-822c-a45c77c0d637.png)

**Comment by zifeo** [comment]
@ianozsvald Can you try with `python3.7`?

**Comment by ianozsvald** [comment]
This works with Python 3.7, here I installed everything using `conda` (I had a problem with conda & Python 3.8: https://github.com/PatrikHlobil/Pandas-Bokeh/issues/64 )

![image](https://user-images.githubusercontent.com/273210/79698483-1bfa4500-8281-11ea-90db-6343481fbb3d.png)

Can you state if you made a fresh environment or if you've upgraded? Providing other version details would help.

**Comment by zifeo** [comment]
Tried on a fresh version and all good. I had a dev version of pandas bokeh (`pip3 install -e pandas_bokeh`) which was presumably broken or too old. Thanks for point this out!

**Comment by PatrikHlobil** [comment]
Hi, 

I couldn't release the conda package for the most recent versions because there were some problems with the package dependencies. Please install via pip at the moment.

Best Patrik
